docs/READMEを変更しました。
NA-67169/tukimi pull request #1
Opened 2024-10-26 08:55 UTC by NA-67169

READMEにサービス内容を記述しました。

2024-10-27 06:38 UTC, tarakish requested changes
確認しました。以下コメントです！

---

- サービス概要
  - 月の満ち欠け情報の提供と、夜景写真の投稿がメインかと思いますが、@NA-67169 さんとしては機能としてどちらをコアとして考えられていますか？
  - 「月の満ち欠けを知りたいだけのユーザー」「夜景写真を投稿、閲覧したいだけのユーザー」も一定数いるのではないかと思い、その場合にどちらをメインにするかでより対象としたいユーザーが明確になり訴求しやすくなるかと思います。

- 機能候補
  - MVPまでに実装する機能と本リリースまでに実装する機能で分けて記載するように修正をお願いします！

2024-10-29 06:43 UTC, NA-67169 commented
レビューありがとうございます！
レビューを参考にして考えてみました！
・サービス概要
夜景写真の撮影など投稿機能をコアとして考えようと思います。
ただ、月関連の情報などは自分が欲しい機能でもあるのでデザインのバランスも考えて作成していきたいと思います。
・機能候補
MVPまでに実装する機能では、コアとなる投稿機能の基本的なシステムまでを作成していきたいと考えています。
本リリースまでに実装する機能では、月関連の情報などを表示するようにしたいと思います。

2024-10-31 10:00 UTC, NA-67169 commented
返信遅くなり申し訳ありません。
課題ページからプルリクエストを再提出できていませんでした。
以後、気をつけます。

2024-11-01 03:08 UTC, ippei-shimizu commented
対応ありがとうございます。以下の点に関してコメントします。
回答及びREADME.mdへの反映をお願いします。
...

- 差別化ポイントの「夜景など夜に関連したものを共有できるようなサイト」ですが、ユーザーが夜景とは全く関係のない投稿をしてしまう可能性もありますが、その点はどのようにして夜景などに関連した投稿だけが行われるようにすることを想定されていますか？

2024-11-01 11:13 UTC, NA-67169 commented
レビューありがとうございます！
___
夜景などに関連したものを投稿してもらうために、
- トップページ、ヘルプページに夜に関連したものを投稿するサイトであることを明示する。
- まず手動で検閲を行い、将来的にAIを利用して検閲を自動化していきたいと思っています。
 - AIに関しては"google vision api"を使用したいと思います。

2024-11-01 12:58 UTC, kashiwagi-rena commented
概ね良いかと思います。LGTMです。

2024-11-02 12:24 UTC, merged